parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: newproj
    database_user: root
    database_password: x
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 319f47e673d233454667aab4eac9bdda
    database_path: null
