parameters:
  ecma_store.example.class: Ecma\StoreBundle\Example
  parameter_name: zrt
services:
  ecma_store.example:
    class: %ecma_store.example.class%
    arguments:
#      - @service_id
      - plain_value
      - %parameter_name%
